/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	// Enable exceptions
	uint32_t* pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault

	uint32_t* pSRAM = (uint32_t*)0x20010000; // Accessing random location in SRAM
	*pSRAM = 0xFFFFFFFF; // Initializing with some invalid value (opcode)

	void (*some_address) (void); // Initializing a void pointer

	some_address = (void*)0x20010001;

	some_address(); // loading the value in PC

    /* Loop forever */
	for(;;);
}
void HardFault_Handler(void) {
	printf("Hard Fault");
	while(1);
}

void MemManage_Handler(void) {
	printf("Memory Management Fault");
	while(1);
}

void BusFault_Handler(void) {
	printf("Bus Fault");
	while(1);
}

void UsageFault_Handler(void) {
	printf("Usage Fault");
	while(1);
}
