/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{
	RCC_AHB1ENR_t volatile * const pClock = (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODER_t volatile * const pMode  = (GPIOx_MODER_t*)0x40020000;
	GPIOx_ODR_t volatile * const pOutput  = (GPIOx_ODR_t*)  0x40020014;

	pClock->gpioaEN = 1;
	pMode->modeR6 = 1;

	while(1) {
		pOutput->odR6 = 1;
		for (int i = 0; i < 100000; ++i);
		pOutput->odR6 = 0;
		for (int i = 0; i < 100000; ++i);
	}

	/* Loop forever */
	for(;;);
}
