/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

__attribute__((naked)) void init_sched_stack(uint32_t stack_top);
void init_task_stack(void);
void init_systick_timer(uint32_t tick_hz);
void enable_processor_faults(void);
uint32_t get_psp_value(void);
__attribute__((naked)) void change_sp_to_psp(void);
void task_delay(uint32_t delay_count);
void led_on(uint8_t led_port);
void led_off(uint8_t led_port);

uint8_t current_task = 1;
uint32_t gtick_count = 0;

typedef struct {
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  task_status;
	void (*task_handle)(void);
}TASK_STRUCT_t;

TASK_STRUCT_t task[MAX_TASK];

void idle_task(void) {
	while(1) {

	}
}

void task1_handler(void) {
	while(1){
		//printf("In Task 1\n");
		led_on(9);
		task_delay(1000);
		led_off(9);
		task_delay(1000);
	}
}

void task2_handler(void) {
	while(1){
		//printf("In Task 2\n");
		led_on(10);
		task_delay(750);
		led_off(10);
		task_delay(750);
	}
}

void task3_handler(void) {
	while(1){
		//printf("In Task 3\n");
		led_on(11);
		task_delay(500);
		led_off(11);
		task_delay(500);
	}
}

void task4_handler(void) {
	while(1){
		//printf("In Task 4\n");
		led_on(12);
		task_delay(250);
		led_off(12);
		task_delay(250);
	}
}

void task_delay(uint32_t delay_count) {
	if (current_task) {
		task[current_task].block_count = gtick_count + delay_count;
		task[current_task].task_status = BLOCKED_STATE;

		uint32_t *pICSR = (uint32_t*)0xE000ED04;
		*pICSR |= (1 << 28);
	}
}

__attribute__((naked)) void init_sched_stack(uint32_t stack_top) {
	__asm volatile("MSR MSP, %0": : "r"(stack_top):);
	__asm volatile("BX LR");
}
uint32_t volatile * const pGPIOA_ODR 	= (uint32_t*) 0x40020014;

void init_led(void) {
	uint32_t volatile * const pAHB1ENR 		= (uint32_t*) 0x40023830;
	uint32_t volatile * const pGPIOA_MODER 	= (uint32_t*) 0x40020000;

	*pAHB1ENR |= 1;
	*pGPIOA_MODER &= ~(0xFF << 18);
	*pGPIOA_MODER |= 0x1540000;
}

void led_on(uint8_t led_port) {
	*pGPIOA_ODR |= (1 << (led_port));
}

void led_off(uint8_t led_port) {
	*pGPIOA_ODR &= ~(1 << (led_port));
}

void init_task_stack(void) {

	task[0].task_status = RUNNING_STATE;
	task[1].task_status = RUNNING_STATE;
	task[2].task_status = RUNNING_STATE;
	task[3].task_status = RUNNING_STATE;
	task[4].task_status = RUNNING_STATE;

	task[0].task_handle = idle_task;
	task[1].task_handle = task1_handler;
	task[2].task_handle = task2_handler;
	task[3].task_handle = task3_handler;
	task[4].task_handle = task4_handler;

	task[0].psp_value = IDLE_STACK_START;
	task[1].psp_value = T1_STACK_START;
	task[2].psp_value = T2_STACK_START;
	task[3].psp_value = T3_STACK_START;
	task[4].psp_value = T4_STACK_START;

	uint32_t* pPSP;
	for (int i = 0; i < MAX_TASK; i++) {
		pPSP = (uint32_t*)task[i].psp_value;

		--pPSP;
		*pPSP = (uint32_t)0x01000000;

		--pPSP;
		*pPSP = (uint32_t)task[i].task_handle;

		--pPSP;
		*pPSP = 0xFFFFFFFD;

		for (int j = 0; j < 13; j++) {
			--pPSP;
			*pPSP = 0;
		}

		task[i].psp_value = (uint32_t)pPSP;
	}
}

int main(void)
{
	enable_processor_faults();

	init_sched_stack(SCHED_STACK_START);

	init_task_stack();

	init_led();

	init_systick_timer(TICK_HZ);

	change_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}

void enable_processor_faults(void) {
	// Enable exceptions
	uint32_t* pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault
}

void init_systick_timer(uint32_t tick_hz) {
	uint32_t count_value = (SYSTICK_TIME / TICK_HZ) - 1;

	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;

	*pSRVR &= ~(0x00FFFFFF);
	*pSRVR |= count_value;

	*pSCSR |= (1 << 1);
	*pSCSR |= (1 << 2);

	*pSCSR |= (1 << 0);

}

uint32_t get_psp_value(void) {
	return task[current_task].psp_value;
}

__attribute__((naked)) void change_sp_to_psp(void) {
	__asm volatile("PUSH {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");

	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL, R0");
	__asm volatile("BX LR");
}

void save_psp_value(uint32_t psp_value) {
	task[current_task].psp_value = psp_value;
}

void update_next_task(void) {
	uint8_t state = BLOCKED_STATE;
	for (int i = 0l; i < MAX_TASK; ++i) {
		current_task++;
		current_task %= MAX_TASK;
		state = task[current_task].task_status;
		if (state && current_task)
			break;
	}

	if (!state)
		current_task = 0;
}

void SysTick_Handler(void) {
	gtick_count++;
	for (int i = 1; i < MAX_TASK; ++i) {
		if (task[i].task_status == BLOCKED_STATE) {
			if (task[i].block_count == gtick_count)
				task[i].task_status = RUNNING_STATE;
		}
	}

	uint32_t *pICSR = (uint32_t*)0xE000ED04;

	*pICSR |= (1 << 28);
}

__attribute__((naked)) void PendSV_Handler(void) {
	/*Save context of current task */
	//1. Get current running task's PSP value
	__asm volatile("MRS R0, PSP");
	//2. Using that PSP value store SF2
	__asm volatile("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}"); //Push original LR to avoid corruption
	//3. Save current value of PSP
	__asm volatile("BL save_psp_value");

	/*Retrieve the context of next task */
	//1. Decide next task to run
	__asm volatile("BL update_next_task");
	//2. Get its past PSP value
	__asm volatile("BL get_psp_value");
	//3. Using that PSP retrieve SF2
	__asm volatile("LDMIA R0!, {R4-R11}");
	//4. Update PSP and exit
	__asm volatile("MSR PSP, R0");

	__asm volatile("POP {LR}");	//Pop original LR saved

	__asm volatile("BX LR");
}

void HardFault_Handler(void) {
	printf("Hard Fault");
	while(1);
}

void MemManage_Handler(void) {
	printf("Memory Management Fault");
	while(1);
}

void BusFault_Handler(void) {
	printf("Bus Fault");
	while(1);
}

void UsageFault_Handler(void) {
	printf("Usage Fault");
	while(1);
}
