/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


int main(void)
{
	__asm volatile("SVC #25");

	register uint32_t data __asm("r0");
    /* Loop forever */
	for(;;);
}

__attribute__ ((naked)) void SVC_Handler(void) {
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBase) {
	printf("IN SVC\n");

	uint8_t *pPC = (uint8_t*)pBase[6];
	printf("PC: 0x%x", *pPC);

	pPC -= 2;

	uint8_t svc_number = *pPC;

	printf("SVC Number: %d", svc_number);

	svc_number += 4;

	pBase[0] = svc_number;
}
